package ec.fugu.ambiente.consultoring.projects;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import ec.gob.ambiente.suia.utils.Constantes;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2 
 */
@WebServiceClient(name = "ProyectoSuia2FacadeService", targetNamespace = "http://projects.consultoring.ambiente.fugu.ec/", wsdlLocation = "http://qa-suia.ambiente.gob.ec:8113/ambienteseam-ambienteseam/ProyectoSuia2Service?wsdl")
public class ProyectoSuia2FacadeService_Service extends Service {

    private final static URL PROYECTOSUIA2FACADESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROYECTOSUIA2FACADESERVICE_EXCEPTION;
    private final static QName PROYECTOSUIA2FACADESERVICE_QNAME = new QName("http://projects.consultoring.ambiente.fugu.ec/", "ProyectoSuia2FacadeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constantes.getAppIntegrationServicesProjectsSuia());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROYECTOSUIA2FACADESERVICE_WSDL_LOCATION = url;
        PROYECTOSUIA2FACADESERVICE_EXCEPTION = e;
    }

	public static URL getServiceUrl() throws MalformedURLException {
		return new URL(Constantes.getAppIntegrationServicesProjectsSuia());
	}

    public ProyectoSuia2FacadeService_Service() throws MalformedURLException {
        super(getServiceUrl(), PROYECTOSUIA2FACADESERVICE_QNAME);
    }

    public ProyectoSuia2FacadeService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROYECTOSUIA2FACADESERVICE_QNAME, features);
    }

    public ProyectoSuia2FacadeService_Service(URL wsdlLocation) {
        super(wsdlLocation, PROYECTOSUIA2FACADESERVICE_QNAME);
    }

    public ProyectoSuia2FacadeService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROYECTOSUIA2FACADESERVICE_QNAME, features);
    }

    public ProyectoSuia2FacadeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProyectoSuia2FacadeService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProyectoSuia2FacadeService
     */
    @WebEndpoint(name = "ProyectoSuia2FacadeServicePort")
    public ProyectoSuia2FacadeService getProyectoSuia2FacadeServicePort() {
        return super.getPort(new QName("http://projects.consultoring.ambiente.fugu.ec/", "ProyectoSuia2FacadeServicePort"), ProyectoSuia2FacadeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProyectoSuia2FacadeService
     */
    @WebEndpoint(name = "ProyectoSuia2FacadeServicePort")
    public ProyectoSuia2FacadeService getProyectoSuia2FacadeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://projects.consultoring.ambiente.fugu.ec/", "ProyectoSuia2FacadeServicePort"), ProyectoSuia2FacadeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROYECTOSUIA2FACADESERVICE_EXCEPTION != null) {
            throw PROYECTOSUIA2FACADESERVICE_EXCEPTION;
        }
        return PROYECTOSUIA2FACADESERVICE_WSDL_LOCATION;
    }

}
