
package ec.fugu.ambiente.consultoring.projects;

import ec.gob.ambiente.suia.utils.Constantes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Suia2ConsultasExternas", targetNamespace = "http://projects.consultoring.ambiente.fugu.ec/", wsdlLocation = "http://qa-suia.ambiente.gob.ec:8113/ambienteseam-ambienteseam/Suia2ConsultasExternas?wsdl")
public class Suia2ConsultasExternas_Service
    extends Service
{

    private final static URL SUIA2CONSULTASEXTERNAS_WSDL_LOCATION;
    private final static WebServiceException SUIA2CONSULTASEXTERNAS_EXCEPTION;
    private final static QName SUIA2CONSULTASEXTERNAS_QNAME = new QName("http://projects.consultoring.ambiente.fugu.ec/", "Suia2ConsultasExternas");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constantes.getAppIntegrationServicesListProjectsSuia());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUIA2CONSULTASEXTERNAS_WSDL_LOCATION = url;
        SUIA2CONSULTASEXTERNAS_EXCEPTION = e;
    }

    public static URL getServiceUrl() throws MalformedURLException {
        return new URL(Constantes.getAppIntegrationServicesListProjectsSuia());
    }

    public Suia2ConsultasExternas_Service() {
        super(__getWsdlLocation(), SUIA2CONSULTASEXTERNAS_QNAME);
    }

    public Suia2ConsultasExternas_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUIA2CONSULTASEXTERNAS_QNAME, features);
    }

    public Suia2ConsultasExternas_Service(URL wsdlLocation) {
        super(wsdlLocation, SUIA2CONSULTASEXTERNAS_QNAME);
    }

    public Suia2ConsultasExternas_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUIA2CONSULTASEXTERNAS_QNAME, features);
    }

    public Suia2ConsultasExternas_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Suia2ConsultasExternas_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Suia2ConsultasExternas
     */
    @WebEndpoint(name = "Suia2ConsultasExternasPort")
    public Suia2ConsultasExternas getSuia2ConsultasExternasPort() {
        return super.getPort(new QName("http://projects.consultoring.ambiente.fugu.ec/", "Suia2ConsultasExternasPort"), Suia2ConsultasExternas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Suia2ConsultasExternas
     */
    @WebEndpoint(name = "Suia2ConsultasExternasPort")
    public Suia2ConsultasExternas getSuia2ConsultasExternasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://projects.consultoring.ambiente.fugu.ec/", "Suia2ConsultasExternasPort"), Suia2ConsultasExternas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUIA2CONSULTASEXTERNAS_EXCEPTION!= null) {
            throw SUIA2CONSULTASEXTERNAS_EXCEPTION;
        }
        return SUIA2CONSULTASEXTERNAS_WSDL_LOCATION;
    }

}
