
package ec.fugu.ambiente.consultoring.retasking;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import ec.gob.ambiente.suia.utils.Constantes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReasignacionTareaMasivaService", targetNamespace = "http://retasking.consultoring.ambiente.fugu.ec/", wsdlLocation = "http://qa-suia.ambiente.gob.ec:8113/ambienteseam-ambienteseam/ReasignacionTareaMasivaService?wsdl")
public class ReasignacionTareaMasivaService_Service
    extends Service
{

    private final static URL REASIGNACIONTAREAMASIVASERVICE_WSDL_LOCATION;
    private final static WebServiceException REASIGNACIONTAREAMASIVASERVICE_EXCEPTION;
    private final static QName REASIGNACIONTAREAMASIVASERVICE_QNAME = new QName("http://retasking.consultoring.ambiente.fugu.ec/", "ReasignacionTareaMasivaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constantes.getAppIntegrationServicesRetaskingSuia());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REASIGNACIONTAREAMASIVASERVICE_WSDL_LOCATION = url;
        REASIGNACIONTAREAMASIVASERVICE_EXCEPTION = e;
    }
    
    public static URL getServiceUrl() throws MalformedURLException {
		return new URL(Constantes.getAppIntegrationServicesRetaskingSuia());
	}

    public ReasignacionTareaMasivaService_Service() throws MalformedURLException {
        super(getServiceUrl(), REASIGNACIONTAREAMASIVASERVICE_QNAME);
    }

    public ReasignacionTareaMasivaService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), REASIGNACIONTAREAMASIVASERVICE_QNAME, features);
    }

    public ReasignacionTareaMasivaService_Service(URL wsdlLocation) {
        super(wsdlLocation, REASIGNACIONTAREAMASIVASERVICE_QNAME);
    }

    public ReasignacionTareaMasivaService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REASIGNACIONTAREAMASIVASERVICE_QNAME, features);
    }

    public ReasignacionTareaMasivaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReasignacionTareaMasivaService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReasignacionTareaMasivaService
     */
    @WebEndpoint(name = "ReasignacionTareaMasivaServicePort")
    public ReasignacionTareaMasivaService getReasignacionTareaMasivaServicePort() {
        return super.getPort(new QName("http://retasking.consultoring.ambiente.fugu.ec/", "ReasignacionTareaMasivaServicePort"), ReasignacionTareaMasivaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReasignacionTareaMasivaService
     */
    @WebEndpoint(name = "ReasignacionTareaMasivaServicePort")
    public ReasignacionTareaMasivaService getReasignacionTareaMasivaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://retasking.consultoring.ambiente.fugu.ec/", "ReasignacionTareaMasivaServicePort"), ReasignacionTareaMasivaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REASIGNACIONTAREAMASIVASERVICE_EXCEPTION!= null) {
            throw REASIGNACIONTAREAMASIVASERVICE_EXCEPTION;
        }
        return REASIGNACIONTAREAMASIVASERVICE_WSDL_LOCATION;
    }

}
