
package ec.fugu.ambiente.consultoring.retasking;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReasignacionTareaMasivaService", targetNamespace = "http://retasking.consultoring.ambiente.fugu.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReasignacionTareaMasivaService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ec.fugu.ambiente.consultoring.retasking.ProyectoLicenciaVo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaTareas", targetNamespace = "http://retasking.consultoring.ambiente.fugu.ec/", className = "ec.fugu.ambiente.consultoring.retasking.ListaTareas")
    @ResponseWrapper(localName = "listaTareasResponse", targetNamespace = "http://retasking.consultoring.ambiente.fugu.ec/", className = "ec.fugu.ambiente.consultoring.retasking.ListaTareasResponse")
    public List<ProyectoLicenciaVo> listaTareas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param proyectoSelecionados
     * @param usuarioAnterior
     * @param usuarioReasignar
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reasignarProyestos", targetNamespace = "http://retasking.consultoring.ambiente.fugu.ec/", className = "ec.fugu.ambiente.consultoring.retasking.ReasignarProyestos")
    @ResponseWrapper(localName = "reasignarProyestosResponse", targetNamespace = "http://retasking.consultoring.ambiente.fugu.ec/", className = "ec.fugu.ambiente.consultoring.retasking.ReasignarProyestosResponse")
    public String reasignarProyestos(
        @WebParam(name = "proyectoSelecionados", targetNamespace = "")
        List<ProyectoLicenciaVo> proyectoSelecionados,
        @WebParam(name = "usuarioAnterior", targetNamespace = "")
        String usuarioAnterior,
        @WebParam(name = "usuarioReasignar", targetNamespace = "")
        String usuarioReasignar);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<ec.fugu.ambiente.consultoring.retasking.UsuarioCarga>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "traerCargaTecnicos", targetNamespace = "http://retasking.consultoring.ambiente.fugu.ec/", className = "ec.fugu.ambiente.consultoring.retasking.TraerCargaTecnicos")
    @ResponseWrapper(localName = "traerCargaTecnicosResponse", targetNamespace = "http://retasking.consultoring.ambiente.fugu.ec/", className = "ec.fugu.ambiente.consultoring.retasking.TraerCargaTecnicosResponse")
    public List<UsuarioCarga> traerCargaTecnicos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte arg1);

}
