
package ec.gob.ambiente.suia.procedimientosadministrativosmaelogin.controller;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaPAWS", targetNamespace = "http://Controller.procedimientosAdministrativosMAELogin.suia.ambiente.gob.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaPAWS {


    /**
     * 
     * @param cIRucPresuntoInfractor
     * @return
     *     returns java.util.List<ec.gob.ambiente.suia.procedimientosadministrativosmaelogin.controller.ProcedimientoAdministrativoVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerRUC", targetNamespace = "http://Controller.procedimientosAdministrativosMAELogin.suia.ambiente.gob.ec/", className = "ec.gob.ambiente.suia.procedimientosadministrativosmaelogin.controller.ObtenerRUC")
    @ResponseWrapper(localName = "obtenerRUCResponse", targetNamespace = "http://Controller.procedimientosAdministrativosMAELogin.suia.ambiente.gob.ec/", className = "ec.gob.ambiente.suia.procedimientosadministrativosmaelogin.controller.ObtenerRUCResponse")
    public List<ProcedimientoAdministrativoVO> obtenerRUC(
        @WebParam(name = "cI_rucPresuntoInfractor", targetNamespace = "")
        String cIRucPresuntoInfractor);

}
