
package ec.gob.ambiente.suia.procedimientosadministrativosmaelogin.controller;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import ec.gob.ambiente.suia.utils.Constantes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "consultaPA", targetNamespace = "http://Controller.procedimientosAdministrativosMAELogin.suia.ambiente.gob.ec/", wsdlLocation = "http://qa-suia.ambiente.gob.ec:8092/procedimientosAdministrativosMAELogin/consultaPA?wsdl")
public class ConsultaPA
    extends Service
{

    private final static URL CONSULTAPA_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPA_EXCEPTION;
    private final static QName CONSULTAPA_QNAME = new QName("http://Controller.procedimientosAdministrativosMAELogin.suia.ambiente.gob.ec/", "consultaPA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://qa-suia.ambiente.gob.ec:8092/procedimientosAdministrativosMAELogin/consultaPA?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPA_WSDL_LOCATION = url;
        CONSULTAPA_EXCEPTION = e;
    }

    public static URL getServiceUrl() throws MalformedURLException {
		return new URL(Constantes.getProcedimientosAdministrativosURL());
	}

	public ConsultaPA() throws MalformedURLException {
		super(getServiceUrl(), CONSULTAPA_QNAME);
	}

    public ConsultaPA(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPA_QNAME, features);
    }

    public ConsultaPA(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPA_QNAME);
    }

    public ConsultaPA(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPA_QNAME, features);
    }

    public ConsultaPA(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPA(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultaPAWS
     */
    @WebEndpoint(name = "ConsultaPAWSPort")
    public ConsultaPAWS getConsultaPAWSPort() {
        return super.getPort(new QName("http://Controller.procedimientosAdministrativosMAELogin.suia.ambiente.gob.ec/", "ConsultaPAWSPort"), ConsultaPAWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPAWS
     */
    @WebEndpoint(name = "ConsultaPAWSPort")
    public ConsultaPAWS getConsultaPAWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Controller.procedimientosAdministrativosMAELogin.suia.ambiente.gob.ec/", "ConsultaPAWSPort"), ConsultaPAWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPA_EXCEPTION!= null) {
            throw CONSULTAPA_EXCEPTION;
        }
        return CONSULTAPA_WSDL_LOCATION;
    }

}
