
package ec.gob.ambiente.hyd.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HidrocarburosWs", targetNamespace = "http://service.hyd.ambiente.gob.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HidrocarburosWs {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://service.hyd.ambiente.gob.ec/", className = "ec.gob.ambiente.hyd.service.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://service.hyd.ambiente.gob.ec/", className = "ec.gob.ambiente.hyd.service.LogoutResponse")
    public void logout();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNamePorcess", targetNamespace = "http://service.hyd.ambiente.gob.ec/", className = "ec.gob.ambiente.hyd.service.GetNamePorcess")
    @ResponseWrapper(localName = "getNamePorcessResponse", targetNamespace = "http://service.hyd.ambiente.gob.ec/", className = "ec.gob.ambiente.hyd.service.GetNamePorcessResponse")
    public String getNamePorcess(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param username
     * @param password
     * @return
     *     returns java.util.List<ec.gob.ambiente.hyd.service.TaskSummaryDto>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskList", targetNamespace = "http://service.hyd.ambiente.gob.ec/", className = "ec.gob.ambiente.hyd.service.GetTaskList")
    @ResponseWrapper(localName = "getTaskListResponse", targetNamespace = "http://service.hyd.ambiente.gob.ec/", className = "ec.gob.ambiente.hyd.service.GetTaskListResponse")
    public List<TaskSummaryDto> getTaskList(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password)
        throws Exception_Exception
    ;

}
