
package ec.gob.ambiente.suia.web.services.financial.financialws.controller;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OnlinePaymentService", targetNamespace = "http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OnlinePaymentService {


    /**
     * 
     * @param nombreConvenio
     * @param numeroCuenta
     * @param usuario
     * @param contrasenia
     * @param codigoBanco
     * @param fechaHora
     * @param idCliente
     * @param nombreCliente
     * @param numeroConvenio
     * @param tipoTransaccion
     * @param oficinaTransaccion
     * @param numeroTransaccionCobis
     * @param monto
     * @return
     *     returns ec.gob.ambiente.suia.web.services.financial.financialws.controller.RespuestaVO
     */
    @WebMethod
    @WebResult(name = "respuesta", targetNamespace = "")
    @RequestWrapper(localName = "setPaymentRegister", targetNamespace = "http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", className = "ec.gob.ambiente.suia.web.services.financial.financialws.controller.SetPaymentRegister")
    @ResponseWrapper(localName = "setPaymentRegisterResponse", targetNamespace = "http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", className = "ec.gob.ambiente.suia.web.services.financial.financialws.controller.SetPaymentRegisterResponse")
    public RespuestaVO setPaymentRegister(
        @WebParam(name = "numeroTransaccionCobis", targetNamespace = "")
        String numeroTransaccionCobis,
        @WebParam(name = "numeroConvenio", targetNamespace = "")
        String numeroConvenio,
        @WebParam(name = "nombreConvenio", targetNamespace = "")
        String nombreConvenio,
        @WebParam(name = "numeroCuenta", targetNamespace = "")
        String numeroCuenta,
        @WebParam(name = "fechaHora", targetNamespace = "")
        String fechaHora,
        @WebParam(name = "idCliente", targetNamespace = "")
        String idCliente,
        @WebParam(name = "nombreCliente", targetNamespace = "")
        String nombreCliente,
        @WebParam(name = "monto", targetNamespace = "")
        String monto,
        @WebParam(name = "oficinaTransaccion", targetNamespace = "")
        String oficinaTransaccion,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "contrasenia", targetNamespace = "")
        String contrasenia,
        @WebParam(name = "codigoBanco", targetNamespace = "")
        String codigoBanco,
        @WebParam(name = "tipoTransaccion", targetNamespace = "")
        String tipoTransaccion);

}
