
package ec.gob.ambiente.suia.web.services.financial.financialws.controller;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import ec.gob.ambiente.suia.utils.Constantes;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OnlinePaymentService", targetNamespace = "http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", wsdlLocation = "http://172.16.0.229:8080/financialWS/OnlinePaymentService/OnlinePaymentService?wsdl")
//@WebServiceClient(name = "OnlinePaymentService", targetNamespace = "http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", wsdlLocation = "http://qa-suia.ambiente.gob.ec:8092/financialWS/OnlinePaymentService/OnlinePaymentService?wsdl")
public class OnlinePaymentService_Service
    extends Service
{

    private final static URL ONLINEPAYMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ONLINEPAYMENTSERVICE_EXCEPTION;
    private final static QName ONLINEPAYMENTSERVICE_QNAME = new QName("http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", "OnlinePaymentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("http://qa-suia.ambiente.gob.ec:8092/financialWS/OnlinePaymentService/OnlinePaymentService?wsdl");
        	 URL baseUrl;
             baseUrl = ec.gob.ambiente.suia.web.services.financial.financialws.controller.OnlinePaymentService_Service.class.getResource(".");
//             url = new URL(baseUrl, "http://qa-suia.ambiente.gob.ec:8092/financialWS/OnlinePaymentService/OnlinePaymentService?wsdl");
             url = new URL(Constantes.getServicePayAddresInsertar());
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ONLINEPAYMENTSERVICE_WSDL_LOCATION = url;
        ONLINEPAYMENTSERVICE_EXCEPTION = e;
    }

    public OnlinePaymentService_Service() {
        super(__getWsdlLocation(), ONLINEPAYMENTSERVICE_QNAME);
    }

    public OnlinePaymentService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ONLINEPAYMENTSERVICE_QNAME, features);
    }

    public OnlinePaymentService_Service(URL wsdlLocation) {
        super(wsdlLocation, ONLINEPAYMENTSERVICE_QNAME);
    }

    public OnlinePaymentService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ONLINEPAYMENTSERVICE_QNAME, features);
    }

    public OnlinePaymentService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnlinePaymentService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OnlinePaymentService
     */
    @WebEndpoint(name = "OnlinePaymentServicePort")
    public OnlinePaymentService getOnlinePaymentServicePort() {
        return super.getPort(new QName("http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", "OnlinePaymentServicePort"), OnlinePaymentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlinePaymentService
     */
    @WebEndpoint(name = "OnlinePaymentServicePort")
    public OnlinePaymentService getOnlinePaymentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.financialWS.financial.services.web.suia.ambiente.gob.ec/", "OnlinePaymentServicePort"), OnlinePaymentService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ONLINEPAYMENTSERVICE_EXCEPTION!= null) {
            throw ONLINEPAYMENTSERVICE_EXCEPTION;
        }
        return ONLINEPAYMENTSERVICE_WSDL_LOCATION;
    }

}
